apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-repo
  description: Repositorio con documentación de ejemplo.
  annotations:
    # Indica dónde buscar la documentación
    backstage.io/techdocs-ref: https://github.com/mframirezfuentes/boardgame-api
spec:
  type: library
  owner: mframirezfuentes@gmail.com
  lifecycle: experimental