version: '3.8'

volumes:
  mongodbdata:
  neo4jdata:

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: boardgame
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend  
  neo4j:
    image: neo4j:5.18.1
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/r@ndomp4ss
    networks:
      - backend
    volumes:
      - neo4jdata:/data
      - neo4jdata:/logs

networks:
  backend:
    driver: bridge